version: '3'

services:
  db:
    container_name: db
    image: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql 
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: php_web
    depends_on:
      - db
    ports:
      - "8100:80"
    tty: true

